server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: sistema-torneos-deportivos

  datasource:
    url: jdbc:postgresql://localhost:5432/torneos_db
    username: ${DB_USER:torneos_user}
    password: ${DB_PASSWORD:torneos_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
    defer-datasource-initialization: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  security:
    require-ssl: false

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:MiClaveSecretaSuperSeguraParaTorneosDeportivos2024}
  expiration: 86400000 # 24 horas en millisegundos

# Logging
logging:
  level:
    com.torneos: DEBUG
    org.springframework.security: DEBUG
    org.flywaydb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/sistema-torneos.log

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

---
# Perfil de desarrollo
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
  flyway:
    clean-disabled: false

---
# Perfil de producción
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    hikari:
      maximum-pool-size: 50
  jpa:
    show-sql: false
  security:
    require-ssl: true

logging:
  level:
    com.torneos: INFO
    org.springframework.security: WARN
